#!/usr/bin/env python3
"""Render deterministic LaTeX tables for official LeRobot MT50 shard results."""

from __future__ import annotations

import argparse
import json
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path
from typing import Any


DIFFICULTY_ORDER = ("easy", "medium", "hard", "very_hard", "unclassified")


@dataclass(frozen=True)
class TaskRow:
    shard: str
    task: str
    difficulty: str
    successes: int
    episodes: int

    @property
    def pct_success(self) -> float:
        return 100.0 * self.successes / self.episodes if self.episodes else float("nan")


def _difficulty_rank(difficulty: str) -> int:
    try:
        return DIFFICULTY_ORDER.index(difficulty)
    except ValueError:
        return len(DIFFICULTY_ORDER)


def _latex_escape(text: str) -> str:
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    return "".join(replacements.get(ch, ch) for ch in text)


def load_difficulty_map(index_path: Path) -> dict[str, str]:
    data = json.loads(index_path.read_text(encoding="utf-8"))
    out: dict[str, str] = {}
    for row in data.get("tasks", []):
        task = row.get("task")
        if task:
            out[task] = row.get("difficulty", "unclassified")
    return out


def collect_rows(run_root: Path, shards: list[str], difficulty_index: Path) -> list[TaskRow]:
    difficulty_by_task = load_difficulty_map(difficulty_index)
    rows: list[TaskRow] = []
    for shard in shards:
        eval_info_path = run_root / shard / "eval_info.json"
        data = json.loads(eval_info_path.read_text(encoding="utf-8"))
        for task_info in data.get("per_task", []):
            task = task_info["task_group"]
            successes = [bool(x) for x in task_info.get("metrics", {}).get("successes", [])]
            rows.append(
                TaskRow(
                    shard=shard,
                    task=task,
                    difficulty=difficulty_by_task.get(task, "unclassified"),
                    successes=sum(successes),
                    episodes=len(successes),
                )
            )
    return sorted(rows, key=lambda r: (_difficulty_rank(r.difficulty), r.task, r.shard))


def aggregate_by_difficulty(rows: list[TaskRow]) -> list[tuple[str, int, int, int]]:
    grouped: dict[str, dict[str, int]] = defaultdict(lambda: {"successes": 0, "episodes": 0, "tasks": 0})
    for row in rows:
        grouped[row.difficulty]["successes"] += row.successes
        grouped[row.difficulty]["episodes"] += row.episodes
        grouped[row.difficulty]["tasks"] += 1

    out: list[tuple[str, int, int, int]] = []
    for difficulty in sorted(grouped, key=_difficulty_rank):
        values = grouped[difficulty]
        out.append((difficulty, values["successes"], values["episodes"], values["tasks"]))
    return out


def _success_cell(successes: int, episodes: int) -> str:
    return f"{successes}/{episodes}"


def _pct_cell(successes: int, episodes: int) -> str:
    pct = 100.0 * successes / episodes if episodes else float("nan")
    return f"{pct:.1f}\\%"


def render_latex(rows: list[TaskRow], *, caption_prefix: str) -> str:
    lines: list[str] = []
    lines.extend(
        [
            "% Generated by scripts/mt50/render_official_lerobot_latex_tables.py",
            "% Do not edit by hand; regenerate from shard eval_info.json files.",
            r"\begin{table}[htbp]",
            r"\centering",
            rf"\caption{{{_latex_escape(caption_prefix)} per-task success.}}",
            r"\begin{tabular}{llrr}",
            r"\hline",
            r"Task & Difficulty & Success & Success (\%) \\",
            r"\hline",
        ]
    )
    for row in rows:
        lines.append(
            " & ".join(
                [
                    _latex_escape(row.task),
                    _latex_escape(row.difficulty),
                    _success_cell(row.successes, row.episodes),
                    _pct_cell(row.successes, row.episodes),
                ]
            )
            + r" \\"
        )
    lines.extend([r"\hline", r"\end{tabular}", r"\end{table}", ""])

    aggregates = aggregate_by_difficulty(rows)
    total_successes = sum(row.successes for row in rows)
    total_episodes = sum(row.episodes for row in rows)
    total_tasks = len(rows)
    lines.extend(
        [
            r"\begin{table}[htbp]",
            r"\centering",
            rf"\caption{{{_latex_escape(caption_prefix)} success by task difficulty.}}",
            r"\begin{tabular}{lrrr}",
            r"\hline",
            r"Difficulty & Success & Success (\%) & Tasks \\",
            r"\hline",
        ]
    )
    for difficulty, successes, episodes, tasks in aggregates:
        lines.append(
            " & ".join(
                [
                    _latex_escape(difficulty),
                    _success_cell(successes, episodes),
                    _pct_cell(successes, episodes),
                    str(tasks),
                ]
            )
            + r" \\"
        )
    lines.append(
        " & ".join(
            [
                "Total",
                _success_cell(total_successes, total_episodes),
                _pct_cell(total_successes, total_episodes),
                str(total_tasks),
            ]
        )
        + r" \\"
    )
    lines.extend([r"\hline", r"\end{tabular}", r"\end{table}", ""])
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--run-root",
        type=Path,
        default=Path("artifacts/MT50_Phase072_official_lerobot_10ep"),
        help="Directory containing shard0/shard1/shard2 eval_info.json files.",
    )
    parser.add_argument("--shards", nargs="+", default=["shard0", "shard1", "shard2"])
    parser.add_argument(
        "--difficulty-index",
        type=Path,
        default=Path("artifacts/MT50_Phase07_500_10ep/MT50_Phase07_index.json"),
        help="Index JSON containing task difficulty labels.",
    )
    parser.add_argument(
        "--caption-prefix",
        default="MT50 Phase072 official LeRobot, 10 episodes",
    )
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()

    rows = collect_rows(args.run_root, list(args.shards), args.difficulty_index)
    latex = render_latex(rows, caption_prefix=args.caption_prefix)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(latex, encoding="utf-8")
    print(f"wrote {args.output} rows={len(rows)}")


if __name__ == "__main__":
    main()
